#!/usr/bin/env bash
#define MAX_ARG_PAGES 32
set -e
export SHELL=$(type -p bash)
. ~/.bashrc
# freemem=`free | awk '{print $4}'`
# freemem=`echo $freemem | cut -d' ' -f4`
# MEMLIMIT=`expr $freemem \/ 4 \* 3`
###############################################
MODULE_NAME=`basename "$0" | tr "[a-z]" "[A-Z]"`
module_name=`basename "$0" | tr "[A-Z]" "[a-z]"`
function beginswith { 
	case $2 in 
		"$1"*) true;; 
		*) false;; 
	esac
}
###############################################
###################
### MODULE INFO ###
###################
DESCRIPTION="bzip2 is a freely available, patent free (see below), high-quality data compressor."
WEBSITE="http://www.bzip.org/index.html"
CITATIONS=""
MODULE_AUTHOR="Noah Gettle"
YEAR_WRITTEN="2016"
###############################################
MODULE_INFO="DESCRIPTION:\n$DESCRIPTION\nWEBSITE:\n$WEBSITE\nCITATION:\n$CITATION"
AUTHOR_INFO="$MODULE_AUTHOR $YEAR_WRITTEN"

function mongerinstall {
	MODULE_NAME=$1
	shift
	MODULE_INFO=$1
	shift
	AUTHOR_INFO=$1
	shift
	module_name=`echo $MODULE_NAME | tr "[A-Z]" "[a-z]"`
	SUBTHREADS=1
	####################################
	############ USAGE #################
	####################################
	usage="SYNOPSIS:\nmonger install $module_name\n$MODULE_INFO\n\
OPTIONS:\n\
  -i | --install_dir [DIR]\tInstallation directory [/usr/local/]\n\
  -f | --force\t\t\tOverwrite existing program executables.\n\	
  -h | --help\t\t\tPrint help message\n\n\
AUTHOR:\n\
$AUTHOR_INFO"

	####################################
	######## INPUT PROCESSING ##########
	####################################
	INSTALL_DIR=/usr/local
	FORCE=FALSE
	while [ "$1" != "" ]
	do
		case $1 in
			-i | --install_dir)	
				shift
				INSTALL_DIR=$1;;
			-f | --force)
				FORCE=TRUE;;
			-h | --help)
				echo -e $usage
				exit 1;;
			*)	
				echo -e "\nMONGER RUN $MODULE_NAME ERROR: $1 is not a valid option.\n$usage"
				exit 1				
		esac
		shift
	done

	####################################

	PATH_SEP=`echo $PATH | sed 's|:| |g'`
	LD_LIBRARY_PATH_SEP=`echo $LD_LIBRARY_PATH | sed 's|:| |g'`
	INCLUDE_SEP=`echo $INCLUDE | sed 's|:| |g'`

	cur_dir=`pwd`
	DOWNLOAD_DIR=$INSTALL_DIR/soft
	mkdir -p $DOWNLOAD_DIR
	####################################
	###### INSTALL DEPENDENCIES ########
	####################################

	###############################################

	####################################
	###### INSTALL MAIN PROGRAM ########
	####################################
	
	########
	# BZIP #
	########
	bzipfile=`find $INCLUDE_SEP -maxdepth 1 -name 'bzlib.h' | head -1`
	if [ "$bzipfile" == "" ] || [ "$FORCE" == "TRUE" ]
	then
		echo -e "> MONGER INSTALL: Installing $MODULE_NAME."
		cd $DOWNLOAD_DIR
		wget http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz
		tar -zxvf $DOWNLOAD_DIR/bzip2-1.0.6.tar.gz
		cd $DOWNLOAD_DIR/bzip2-1.0.6
		make
		make clean
		make -f Makefile-libbz2_so
		make install PREFIX=$INSTALL_DIR
		rm -f $DOWNLOAD_DIR/bzip2-1.0.6.tar.gz
		BZIP_DIR=$INSTALL_DIR
	else
		echo "> MONGER INSTALL: $MODULE_NAME already installed. Skipping..."
		BZIP_DIR=`dirname $bzipfile`
		BZIP_DIR=`dirname $BZIP_DIR`
	fi
	if `grep -q "export BZIP_DIR=" ~/.bashrc`
	then
		sed -i "s|export BZIP_DIR=.*|export BZIP_DIR=$BZIP_DIR|" ~/.bashrc
	else
		echo "export BZIP_DIR=$BZIP_DIR" >> ~/.bashrc
	fi

	if ! `echo "$LDFLAGS" | grep -q "\-L$BZIP2_DIR/lib"`
	then
		export LDFLAGS="$LDFLAGS -L$BZIP_DIR/lib"
	fi
	if ! `echo $CFLAGS | grep -q "\-I$BZIP_DIR/include"`
	then
		export CFLAGS="$CFLAGS -I$BZIP_DIR/include"
	fi
}

############################################################
if [ "$1" == "run" ]
then
	shift
	run "$MODULE_NAME" "$MODULE_INFO" "$AUTHOR_INFO" $*
elif [ "$1" == "install" ]
then
	shift
	mongerinstall "$MODULE_NAME" "$MODULE_INFO" "$AUTHOR_INFO" $*
else
	echo -e \
"SYNOPSIS:\n\
monger [run|install] $module_name\n$MODULE_INFO\n$AUTHOR_INFO"
	exit 1
fi