#!/usr/bin/env bash
#define MAX_ARG_PAGES 32
set -e
export SHELL=$(type -p bash)
. ~/.bashrc
# freemem=`free | awk '{print $4}'`
# freemem=`echo $freemem | cut -d' ' -f4`
# MEMLIMIT=`expr $freemem \/ 4 \* 3`
###############################################
MODULE_NAME=`basename "$0" | tr "[a-z]" "[A-Z]"`
module_name=`basename "$0" | tr "[A-Z]" "[a-z]"`
function beginswith { 
	case $2 in 
		"$1"*) true;; 
		*) false;; 
	esac
}
###############################################
###################
### MODULE INFO ###
###################
DESCRIPTION="The ncurses (new curses) library is a free software emulation of curses in System V Release 4.0 (SVr4), and more."
WEBSITE="https://www.gnu.org/software/ncurses/"
CITATIONS=""
MODULE_AUTHOR="Noah Gettle"
YEAR_WRITTEN="2016"
current_version="ncurses-6.0"
###############################################
MODULE_INFO="DESCRIPTION:\n$DESCRIPTION\nWEBSITE:\n$WEBSITE\nCITATION:\n$CITATION"
AUTHOR_INFO="$MODULE_AUTHOR $YEAR_WRITTEN"

function mongerinstall {
	MODULE_NAME=$1
	shift
	MODULE_INFO=$1
	shift
	AUTHOR_INFO=$1
	shift
	module_name=`echo $MODULE_NAME | tr "[A-Z]" "[a-z]"`
	SUBTHREADS=1
	####################################
	############ USAGE #################
	####################################
	usage="SYNOPSIS:\nmonger install $module_name\n$MODULE_INFO\n\
OPTIONS:\n\
  -i | --install_dir [DIR]\tInstallation directory [/usr/local/]\n\
  -f | --force\t\t\tOverwrite existing program executables.\n\	
  -h | --help\t\t\tPrint help message\n\n\
AUTHOR:\n\
$AUTHOR_INFO"

	####################################
	######## INPUT PROCESSING ##########
	####################################
	INSTALL_DIR=/usr/local
	FORCE=FALSE
	while [ "$1" != "" ]
	do
		case $1 in
			-i | --install_dir)	
				shift
				INSTALL_DIR=$1;;
			-f | --force)
				FORCE=TRUE;;
			-h | --help)
				echo -e $usage
				exit 1;;
			*)	
				echo -e "\nMONGER RUN $MODULE_NAME ERROR: $1 is not a valid option.\n$usage"
				exit 1				
		esac
		shift
	done

	####################################

	PATH_SEP=`echo $PATH | sed 's|:| |g'`
	LD_LIBRARY_PATH_SEP=`echo $LD_LIBRARY_PATH | sed 's|:| |g'`
	INCLUDE_SEP=`echo $INCLUDE | sed 's|:| |g'`

	cur_dir=`pwd`
	DOWNLOAD_DIR=$INSTALL_DIR/soft
	mkdir -p $DOWNLOAD_DIR

	####################################
	###### INSTALL DEPENDENCIES ########
	####################################

	###############################################

	####################################
	###### INSTALL MAIN PROGRAM ########
	####################################
	
	###########
	# NCURSES #
	###########
	libncursesafile=`find $LD_LIBRARY_PATH_SEP -maxdepth 1 -name 'libncurses.a'`
	libncursesgafile=`find $LD_LIBRARY_PATH_SEP -maxdepth 1 -name 'libncurses_g.a'`
	libncursesppafile=`find $LD_LIBRARY_PATH_SEP -maxdepth 1 -name 'libncurses++.a'`
	libncursesppgafile=`find $LD_LIBRARY_PATH_SEP -maxdepth 1 -name 'libncurses++_g.a'`
	ncursesdir=`find $INCLUDE_SEP -maxdepth 1 -name 'ncurses' -type d`
	if [ "$libncursesafile" == "" ] || [ "$libncursesgafile" == "" ]\
		 || [ "$libncursesppafile" == "" ] || [ "$libncursesppgafile" == "" ]\
			 || [ "$ncursesdir" == "" ]\
				 || [ "$FORCE" == "TRUE" ]
	then
		echo -e "> MONGER INSTALL: Installing $MODULE_NAME."
		cd $DOWNLOAD_DIR
		if ! test -d $DOWNLOAD_DIR/$current_version
		then
			if ! test -f $DOWNLOAD_DIR/$current_version.tar.gz
			then
				wget http://ftp.gnu.org/gnu/ncurses/$current_version.tar.gz
			fi
			tar -zxvf $DOWNLOAD_DIR/$current_version.tar.gz
		fi 
		cd $DOWNLOAD_DIR/$current_version
		./configure --prefix=$INSTALL_DIR
		make
		make install
		rm $DOWNLOAD_DIR/$current_version.tar.gz
	else
		echo "> MONGER INSTALL: $MODULE_NAME already installed. Skipping..."
	fi
}

############################################################
if [ "$1" == "run" ]
then
	shift
	run "$MODULE_NAME" "$MODULE_INFO" "$AUTHOR_INFO" $*
elif [ "$1" == "install" ]
then
	shift
	mongerinstall "$MODULE_NAME" "$MODULE_INFO" "$AUTHOR_INFO" $*
else
	echo -e \
"SYNOPSIS:\n\
monger [run|install] $module_name\n$MODULE_INFO\n$AUTHOR_INFO"
	exit 1
fi