#!/usr/bin/env bash
#define MAX_ARG_PAGES 32
set -e
export SHELL=$(type -p bash)
# freemem=`free | awk '{print $4}'`
# freemem=`echo $freemem | cut -d' ' -f4`
# MEMLIMIT=`expr $freemem \/ 4 \* 3`
###############################################
MODULE_NAME=`basename "$0" | tr "[a-z]" "[A-Z]"`
function beginswith { 
	case $2 in 
		"$1"*) true;; 
		*) false;; 
	esac
}
###############################################

function mongerinstall {
	####################################
	############ USAGE #################
	####################################
	usage=\
"SYNOPSIS:\n\
monger install parallel\n\n\
DESCRIPTION:\n\
Installer for GNU Parallel and its dependencies.\n\n\
PARALLEL DESCRIPTION:\n\
GNU parallel is a shell tool for executing jobs in parallel using one or more computers.\n\
WEBSITE:\n\
https://www.gnu.org/software/parallel/\n\n\
CITATION:\n\
Tange, O. 2011.   
OPTIONS:\n\
  -i | --install_dir [DIR]\tInstallation directory [/usr/local/]\n\
  -f | --force\t\t\tOverwrite existing program executables.\n\
  -h | --help\t\t\tPrint help message\n\n\
AUTHOR:\n\
Noah Gettle 2016"

	####################################
	######## INPUT PROCESSING ##########
	####################################
	MODULE_NAME=$1
	shift
	INSTALL_DIR=/usr/local
	FORCE=FALSE
	while [ "$1" != "" ]
	do
		case $1 in
			-i | --install_dir)
				if ! `beginswith "-" $2`
				then
					shift
					INSTALL_DIR=$1
				fi;;
			-f | --force)	FORCE=TRUE;;
			-h | --help)	echo -e $usage
							exit 1;;
			*)				echo -e "$1 not recognized as a valid option.\nUse option \"-h\" for more help."
							exit 1						
		esac
		shift
	done

	####################################

	PATH_SEP=`echo $PATH | sed 's|:| |g'`
	LD_LIBRARY_PATH_SEP=`echo $LD_LIBRARY_PATH | sed 's|:| |g'`
	INCLUDE_SEP=`echo $INCLUDE | sed 's|:| |g'`

	cur_dir=`pwd`
	DOWNLOAD_DIR=$INSTALL_DIR/soft
	mkdir -p $DOWNLOAD_DIR

	###############################################

	####################################
	###### INSTALL DEPENDENCIES ########
	####################################

	###############################################

	####################################
	###### INSTALL MAIN PROGRAM ########
	####################################

	############
	# PARALLEL #
	############
	if ! type "parallel" >/dev/null 2>/dev/null || [ $FORCE == "TRUE" ]
	then
		echo -e "> MONGER INSTALL: Installing $MODULE_NAME."
		cd $DOWNLOAD_DIR
		if ! test -f $DOWNLOAD_DIR/parallel-latest.tar.bz2
		then
			wget ftp://ftp.gnu.org/gnu/parallel/parallel-latest.tar.bz2
		fi
		rm -rf $DOWNLOAD_DIR/parallel-20*
		tar -xjvf $DOWNLOAD_DIR/parallel-latest.tar.bz2
		cd $DOWNLOAD_DIR/parallel-20*
		./configure --prefix $INSTALL_DIR && make && make install
		parallel --citation
		rm -rf $DOWNLOAD_DIR/parallel-latest.tar.bz2
		if ! type "parallel" >/dev/null 2>/dev/null 
		then
			echo "MONGER INSTALL ERROR: Something went wrong when installing PARALLEL. Sorry, but you may need to try manual installation."
			exit 1
		fi
	else
		echo "> MONGER INSTALL: $MODULE_NAME already installed. Skipping..."
	fi
}

############################################################
if [ "$1" == "run" ]
then
	shift
	run $MODULE_NAME $*
elif [ "$1" == "install" ]
then
	shift
	mongerinstall $MODULE_NAME $*
else
	echo -e "MONGER $MODULE_NAME ERROR: You must specify either \"run\" or \"install\""
	exit 1
fi