#!/usr/bin/env bash
#define MAX_ARG_PAGES 32
set -e
export SHELL=$(type -p bash)
. ~/.bashrc
# freemem=`free | awk '{print $4}'`
# freemem=`echo $freemem | cut -d' ' -f4`
# MEMLIMIT=`expr $freemem \/ 4 \* 3`
export _JAVA_OPTIONS=-Xmx2g
###############################################
MODULE_NAME=`basename "$0" | tr "[a-z]" "[A-Z]"`
module_name=`basename "$0" | tr "[A-Z]" "[a-z]"`
function beginswith { 
	case $2 in 
		"$1"*) true;; 
		*) false;; 
	esac
}
###############################################
###################
### MODULE INFO ###
###################
DESCRIPTION="The PCRE library is a set of functions that implement regular expression pattern matching using the same syntax and semantics as Perl 5."
WEBSITE="http://pcre.org/"
CITATIONS=""
MODULE_AUTHOR="Noah Gettle"
YEAR_WRITTEN="2016"
current_version="pcre-8.40"
###############################################
MODULE_INFO="DESCRIPTION:\n$DESCRIPTION\nWEBSITE:\n$WEBSITE\nCITATION:\n$CITATION"
AUTHOR_INFO="$MODULE_AUTHOR $YEAR_WRITTEN"

function mongerinstall {
	MODULE_NAME=$1
	shift
	MODULE_INFO=$1
	shift
	AUTHOR_INFO=$1
	shift
	module_name=`echo $MODULE_NAME | tr "[A-Z]" "[a-z]"`
	SUBTHREADS=1
	####################################
	############ USAGE #################
	####################################
	usage="SYNOPSIS:\nmonger install $module_name\n$MODULE_INFO\n\
OPTIONS:\n\
  -i | --install_dir [DIR]\tInstallation directory [/usr/local/]\n\
  -f | --force\t\t\tOverwrite existing program executables.\n\	
  -h | --help\t\t\tPrint help message\n\n\
AUTHOR:\n\
$AUTHOR_INFO"

	####################################
	######## INPUT PROCESSING ##########
	####################################
	INSTALL_DIR=/usr/local
	FORCE=FALSE
	while [ "$1" != "" ]
	do
		case $1 in
			-i | --install_dir)	
				shift
				INSTALL_DIR=$1;;
			-f | --force)
				FORCE=TRUE;;
			-h | --help)
				echo -e $usage
				exit 1;;
			*)	
				echo -e "\nMONGER RUN $MODULE_NAME ERROR: $1 is not a valid option.\n$usage"
				exit 1				
		esac
		shift
	done

	####################################

	PATH_SEP=`echo $PATH | sed 's|:| |g'`
	LD_LIBRARY_PATH_SEP=`echo $LD_LIBRARY_PATH | sed 's|:| |g'`
	INCLUDE_SEP=`echo $INCLUDE | sed 's|:| |g'`

	cur_dir=`pwd`
	DOWNLOAD_DIR=$INSTALL_DIR/soft
	mkdir -p $DOWNLOAD_DIR

	####################################
	####### INSTALL DEPENDENCIES #######
	####################################

	###############################################

	####################################
	####### INSTALL MAIN PROGRAM #######
	####################################

	########
	# PCRE #
	########
	pcreafile=`find $LD_LIBRARY_PATH_SEP -maxdepth 1 -name 'libpcre.a' | head -1`
	pcrepcfile=`find $LD_LIBRARY_PATH_SEP -maxdepth 2 -name 'libpcre.pc'`
	pcrecppafile=`find $LD_LIBRARY_PATH_SEP -maxdepth 1 -name 'libpcrecpp.a'`
	pcrecpppcfile=`find $LD_LIBRARY_PATH_SEP -maxdepth 2 -name 'libpcrecpp.pc'`
	pcreposixafile=`find $LD_LIBRARY_PATH_SEP -maxdepth 1 -name 'libpcreposix.a'`
	pcreposixpcfile=`find $LD_LIBRARY_PATH_SEP -maxdepth 2 -name 'libpcreposix.pc'`
	pcrehfile=`find $INCLUDE_SEP -maxdepth 1 -name 'pcre.h'`
	pcrecpphfile=`find $INCLUDE_SEP -maxdepth 1 -name 'pcrecpp.h'`
	pcreposixhfile=`find $INCLUDE_SEP -maxdepth 1 -name 'pcreposix.h'`
	if [ "$pcreafile" == "" ] || [ "$pcrepcfile" == "" ] \
		|| [ "$pcrecppafile" == "" ] || [ "$pcrecpppcfile" == "" ] \
		|| [ "$pcreposixafile" == "" ] || [ "$pcreposixpcfile" == "" ] \
		|| [ "$pcrehfile" == "" ] || [ "$pcrecpphfile" == "" ] || [ "$pcreposixhfile" == "" ] \
		|| [ $FORCE == "TRUE" ]
	then
		echo -e "> MONGER INSTALL: Installing $MODULE_NAME."
		cd $DOWNLOAD_DIR
		if ! test -f $DOWNLOAD_DIR/$current_version.tar.gz
		then
			wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/$current_version.tar.gz
		fi
		tar -zxvf $DOWNLOAD_DIR/$current_version.tar.gz
		cd $DOWNLOAD_DIR/$current_version
		./configure --prefix=$INSTALL_DIR --enable-utf8 --enable-unicode-properties
		make
		make install
		rm $DOWNLOAD_DIR/$current_version.tar.gz
		PCRE_DIR=$INSTALL_DIR
	else
		echo "> MONGER INSTALL: $MODULE_NAME already installed. Skipping..."
		PCRE_DIR=`dirname $pcreafile`
		PCRE_DIR=`dirname $PCRE_DIR`
	fi
	
	if `grep -q "export PCRE_DIR=" ~/.bashrc`
	then
		sed -i "s|export PCRE_DIR=.*|export PCRE_DIR=$PCRE_DIR|" ~/.bashrc
	else
		echo "export PCRE_DIR=$PCRE_DIR" >> ~/.bashrc
	fi
}


############################################################
if [ "$1" == "run" ]
then
	shift
	run "$MODULE_NAME" "$MODULE_INFO" "$AUTHOR_INFO" $*
elif [ "$1" == "install" ]
then
	shift
	mongerinstall "$MODULE_NAME" "$MODULE_INFO" "$AUTHOR_INFO" $*
else
	echo -e \
"SYNOPSIS:\n\
monger [run|install] $module_name\n$MODULE_INFO\n$AUTHOR_INFO"
	exit 1
fi