#!/usr/bin/env bash
#define MAX_ARG_PAGES 32
set -e
export SHELL=$(type -p bash)
# freemem=`free | awk '{print $4}'`
# freemem=`echo $freemem | cut -d' ' -f4`
# MEMLIMIT=`expr $freemem \/ 4 \* 3`
###############################################
MODULE_NAME=`basename "$0" | tr "[a-z]" "[A-Z]"`
function beginswith { 
	case $2 in 
		"$1"*) true;; 
		*) false;; 
	esac
}
###############################################
function mongerinstall {
	####################################
	############ USAGE #################
	####################################
	usage=\
"SYNOPSIS:\n\
monger install picard\n\n\
DESCRIPTION:\n\
Installer for Picard and its dependencies.\n\n\
PICARD DESCRIPTION:\n\
Picard is a set of command line tools for manipulating high-throughput sequencing (HTS) data and formats such as SAM/BAM/CRAM and VCF.\n\n\
WEBSITE:\n\
https://broadinstitute.github.io/picard/\n\n\
CITATION:\n\
OPTIONS:\n\
  -i | --install_dir [DIR]\tInstallation directory [/usr/local/]\n\
  -f | --force\t\t\tOverwrite existing program executables.\n\
  -h | --help\t\t\tPrint help message\n\n\
AUTHOR:\n\
Noah Gettle 2016"
  
	####################################
	######## INPUT PROCESSING ##########
	####################################
	MODULE_NAME=$1
	shift
	INSTALL_DIR=/usr/local
	FORCE=FALSE
	while [ "$1" != "" ]
	do
		case $1 in
			-i | --install_dir)
				if ! `beginswith "-" $2`
				then
					shift
					INSTALL_DIR=$1
				fi;;
			-f | --force)	FORCE=TRUE;;
			-h | --help)	echo -e $usage
							exit 1;;
			*)				echo -e "$1 not recognized as a valid option.\nUse option \"-h\" for more help."
							exit 1						
		esac
		shift
	done

	####################################

	PATH_SEP=`echo $PATH | sed 's|:| |g'`
	LD_LIBRARY_PATH_SEP=`echo $LD_LIBRARY_PATH | sed 's|:| |g'`
	INCLUDE_SEP=`echo $INCLUDE | sed 's|:| |g'`

	cur_dir=`pwd`
	DOWNLOAD_DIR=$INSTALL_DIR/soft
	mkdir -p $DOWNLOAD_DIR

	###############################################

	####################################
	###### INSTALL DEPENDENCIES ########
	####################################

	###############################################

	####################################
	###### INSTALL MAIN PROGRAM ########
	####################################

	##########
	# PICARD #
	##########
	if ! type "picard.jar" >/dev/null 2>/dev/null || [ "$FORCE" == "TRUE" ]
	then
		echo -e "> MONGER INSTALL: Installing $MODULE_NAME."
		cd $INSTALL_DIR/bin
		if ! test -f $INSTALL_DIR/bin/picard.jar
		then
			wget https://github.com/broadinstitute/picard/releases/download/2.6.0/picard.jar
		fi
		chmod -R 755 $INSTALL_DIR/bin/picard.jar
		if ! grep "alias picard=" ~/.bashrc > /dev/null
		then
			echo -e "alias picard=\"java -jar $INSTALL_DIR/bin/picard.jar\"" >> ~/.bashrc
		else
			installpath=$(echo $INSTALL_DIR | sed 's|\/|\\\/|g')
			newline="alias picard=\"java -jar $installpath\/bin\/picard.jar\""
			sed -i "s|alias picard=.*|$newline|" ~/.bashrc
		fi
		. ~/.bashrc
	else
		echo "> MONGER INSTALL: $MODULE_NAME already installed. Skipping..."
	fi
}

############################################################
if [ "$1" == "run" ]
then
	shift
	run $MODULE_NAME $*
elif [ "$1" == "install" ]
then
	shift
	mongerinstall $MODULE_NAME $*
else
	echo -e "MONGER $MODULE_NAME ERROR: You must specify either \"run\" or \"install\""
	exit 1
fi